var fName = "amit";
var score1 = 50;
var score2 = 50.55;
var sum = score1 + score2;
console.log("name : " + fName);
console.log("score1 : " + score1);
console.log("score2 : " + score2);
console.log("sum : " + sum);
var bname;
console.log("value bname is " + bname);
var cname = "Amit1";
console.log("value of cname " + cname);
var lname;
